### ISSUE TITLE
https://mkesting.github.io/jautodoc-update/latest/

### ISSUE THREAD

**Issue by fzimmerli** [mkesting/jautodoc#6]
Hi Martin,

We came across the problem that the link in the composit.xml:

https://dl.bintray.com/mkesting/jautodoc/update/latest"/>

Is no longer working. May you can correct this.

Regards,

Frank

**Comment by mkesting** [comment]
Hi Frank,
the update url changed, because Bintray is no longer available. Im not sure, when you get an error, but maybe you need to change the url in Eclipse under "Preferences->Install/Update->Available Software Sites". New url:

https://mkesting.github.io/jautodoc-update/latest/

Otherwise, please give some more details about your problem.

**Comment by fzimmerli** [comment]
Thank you. That helped.
