### ISSUE TITLE
Update site is not found

### ISSUE THREAD

**Issue by cristcost** [mkesting/jautodoc#7]
Hi!

I'm installing from eclipse marketplace but the update site is not working and returns a 404:

https://mkesting.github.io/jautodoc-update/latest/

**Comment by mkesting** [comment]
Hi Cristiano,
I checked the site and everything seems to be ok. 404 in browser is normal, because there is no index file. Eclipse is looking for files like 

https://mkesting.github.io/jautodoc-update/latest/compositeContent.xml

So if you still have the problem, please give some more details about the error message in Eclipse.
